version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./storage:/app/storage
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    command: php -S 0.0.0.0:8000 -t public

  # Optional: Add Redis for caching/queues later
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
